config/routes.rb
Cms::Application.routes.draw do
  devise_for :users, :controllers => { :sessions => "users/sessions" }, :path => "/",
    :path_names => { :sign_in => 'login'}
  
  resources :pages
  resources :articles
  resources :categories

  match "/show/:id" => "welcome#show"

  root :to => 'welcome#index'

end

app/models/category.rb
# -*- encoding: utf-8 -*-
class Category < ActiveRecord::Base
  acts_as_nested_set
  attr_accessible :name, :parent_id, :ctype, :position, :content
  attr_accessor :content, :page_content

  before_save :update_page_content

  class << self
    attr_accessor :ctypes
  end

  has_one :page
  has_one :articles

  self.ctypes = [['无页面', 'none'], ['页面', 'page'], ['列表', 'list']]

  validates :ctype, :inclusion => { :in => ['none', 'page', 'list'] }

  def content
    self.page.content if self.page
  end

  def content=(content)
    self.page_content = content
  end



  def update_page_content
    if !self.new_record? && self.ctype == "page"
      page = self.page || Page.new
      page.category = self
      page.content = self.page_content
      page.save!
    end
  end

  
end

app/controllers/categories_controller.rb
# -*- encoding: utf-8 -*-
class CategoriesController < ApplicationController
  before_filter :authenticate_user!, :except => "show"
  
  layout "admin.html.erb"

  before_filter  :init_navigation, :only => "show"

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    @current_c = @category
    @category_child =  @category.depth == 1 ?  @current_c.children  : @current_c.parent.children
    respond_to do |format|
      format.html {
      }
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        page = Page.new(:content => @category.content )
        page.category = @category
        page.save
        
        format.html { redirect_to @category, notice: '目录创建成功.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])
    #page = @category.page
    respond_to do |format|
      if @category.update_attributes(params[:category])
        
        #page.update_attribute(:content, @category.content) if page
        #Rails.logger.info page.inpsect

        format.html { redirect_to @category, notice: '目录修改成功.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ctype %><br />
    <%= f.select :ctype, Category.ctypes %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br />
    <%= f.select :parent_id, nested_set_options(Category, @category) {|i| "#{'-' * i.level} #{i.name}" } %>
  </div>
  <div id="category_page_content" class="field <%="hide" if @category.ctype != 'page'  %>">
    <%= f.kindeditor :content, :width => 800, :height => 300 %>
  </div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/categories/edit.html.erb
<h3>修改分类</h3>

<%= render 'form' %>

<%= link_to '显示', @category %> |
<%= link_to '返回', categories_path %>

app/views/categories/index.html.erb
<h3>简单的说明</h3>

导航的分类有三种： 无页面, 页面， 列表。<br/>
无页面： 就是没有页面， 该导航使用的是它的第一个子类的页面<br/>
页面： 就是该导航分类只有一个页面<br/>
列表： 该导航分类有很多页面，如 新闻<br/>


<br/>
祝您使用愉快。
<br/>

<br/>
<%= link_to '新建导航分类', new_category_path %>

app/views/categories/new.html.erb
<h1>新建分类</h1>

<%= render 'form' %>

<%= link_to '返回', categories_path %>